### PR TITLE
DLS release 2 4

### PR DESCRIPTION
**Pull request by ajgdls**
Pull request for DLS release 2-4.  Adding @ulrikpedersen for review of the changes.

### CODE REVIEW

**Comment by ajgdls** [comment]
Add @ajf67d to monitor NDTransfer plugin screen inclusion.

**Comment by ulrikpedersen** [comment]
Hi @ajgdls - just one question: does the "Enabled" -> "ENABLED" change not require an equivalent change to the DLS IOC builder?

**Comment by ajgdls** [comment]
Hi @ulrikpedersen, there are no references to Enabled within builder.py in ADCore.  As it is defined as a macro in the template I believe it's all picked up by autosubstitution.  Interestingly it is referenced in other dependent modules (adUtil), but perhaps only for historical reasons. @thomascobb added in case my comment doesn't agree with how @thomascobb expects builder to work.

**Comment by thomascobb** [comment]
For all the things in ADCore, there is no change because the string Enabled appears in each IOC. This means that each IOC will need to change if they have set Enabled=1. Fortunately, most people use adUtil.gdaPlugins, so we only need to modify that. The only other place that references Enabled is ffmpegServer, which changes the default to 1. This needs to be changed...

Thanks,

## Tom Cobb    

+44 (0)1235 778582    

> -----Original Message-----
> From: Alan Greer [mailto:notifications@github.com]
> Sent: 15 March 2016 15:18
> To: dls-controls/ADCore
> Cc: Cobb, Tom (DLSLtd,RAL,TEC)
> Subject: Re: [ADCore] DLS release 2 4 (#2)
> 
> Hi @ulrikpedersen https://github.com/ulrikpedersen , there are no
> references to Enabled within builder.py in ADCore. As it is defined as a
> macro in the template I believe it's all picked up by autosubstitution.
> Interestingly it is referenced in other dependent modules (adUtil), but
> perhaps only for historical reasons. @thomascobb
> https://github.com/thomascobb  added in case my comment doesn't
> agree with how @thomascobb https://github.com/thomascobb  expects
> builder to work.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dls-controls/ADCore/pull/2#issuecomment-196871748
> <https://github.com/notifications/beacon/AHWR5Knae7NI6Ttb9Wkvm15K4
> cpa0mw3ks5pts26gaJpZM4Hw_aN.gif>

## 

This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom

**Comment by ajgdls** [comment]
Hi @ulrikpedersen, I've pushed the additional commits to update ADCore to reference latest pre1 HDF5 library, remove pvCommonCPP after Dave suggested it is not required, and added additional NDStdArray detail screen that got dropped by mistake when converting from areaDetector 1-9 to ADCore 2-x.

**Comment by ulrikpedersen** [comment]
OK, great. In fact the removal of pvCommonCPP is required in order to use avoid using its copy of the boost libs!

Please go ahead and merge when you're ready.

**Pull request merged**
