### PR TITLE
Fixed a memory leak in the Pos plugin.

### PR DESCRIPTION
**Pull request by blaz-kranjc**
See pull request #257 in areaDetector/ADCore.

### CODE REVIEW

**Comment by willrogers** [comment]
It's a bit harsh to call it the POS plugin.

**Comment by ulrikpedersen** [comment]
> It's a bit harsh to call it the POS plugin.

wut? ... point of sale ...?

**Comment by ulrikpedersen** [comment]
FYI I'm reviewing the change-set on PR areaDetector/ADCore#257

**Comment by GDYendell** [comment]
I have tested it and this change will merge/rebase cleanly, so I am going to merge 2-6 into master. @blaz-kranjc could you update the branch from master once I do so.

**Comment by blaz-kranjc** [comment]
Hi Gary,
I'll update this PR with the changes from areaDetector/ADCore#257 and rebase it on top of the new master when you are done.

**Comment by blaz-kranjc** [comment]
I will wait until we update the asyn to 4-31. This way we can merge in the proper version of this fix.

**Comment by GDYendell** [comment]
@blaz-kranjc, could you point this PR at dls-controls:dls-master please. I think only you can do that. I will merge this just before releasing ADCore 2-6dls1, which will build against asyn 4-31, is that what you were expecting for this?

**Comment by ulrikpedersen** [comment]
Hi Gary. You can also just import the branch from Blaz repo to dls-controls and create a new PR.

**Comment by blaz-kranjc** [comment]
@GDYendell this should work. Sorry for the mess.

**Comment by ulrikpedersen** [comment]
Thanks @blaz-kranjc

**Comment by GDYendell** [comment]
I have updated the ADCore dependencies ready for release 2-6dls1. Merging now.

**Pull request merged**
