### PR TITLE
Vendor update R2-4

### PR DESCRIPTION
**Pull request by ajgdls**

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
Hi @ajgdls,

I guess the big question is: does it build and run for us? If so then, then lets merge :smiley: 

Cheers,
Ulrik

**Comment by ajgdls** [comment]
Hi @ulrikpedersen I have generated an example IOC using this and the ADExample, which was working.  But I think I would like to do this on a Monday morning, not a Friday afternoon so I will check one final time on Monday that the test IOC builds and runs on linux and windows, and then complete the request.

**Comment by ulrikpedersen** [comment]
Yup, sounds very sensible :smile:

**Comment by ulrikpedersen** [comment]
OK, as agreed per telephone just now: we'll wait to do this merge/vendor update until after the "swmr" and "position_support_fix" branches have been merged into dls-controls/master - and dls-releases been made (i.e. after the next integratathon).

**Comment by ajgdls** [comment]
Hi @ulrikpedersen I realise now that this pull request was already open for the vendor update.  I guess I'm asking you to re-review this again now I have merged "swmr" and "position_support_fix" branches.

**Comment by ulrikpedersen** [comment]
I'm looking through the last commit 5a38837 and I can't see (at a glance at least) what you're replacing the simDetector with?

**Comment by ajgdls** [comment]
The SimulatedDetectorWrapper class has been replaced with a simple asynPortDriver class.  The detector was not actually used to produce frames, these are supplied by the test harness and so the only reason for the original Wrapper was to ensure the downstream plugin did not fail as it requires a port to connect to.  The asynPortDriver provides this port.

**Comment by ulrikpedersen** [comment]
Ah yes of course.Thanks for the explanation. Please go ahead and do the merge when you have time for it Alan.

**Pull request merged**
