### PR TITLE
Time series plugins

### PR DESCRIPTION
**Pull request by BenBradnick**
Added builder support for NDTimeSeries and NDFFT plugins, and created relevant EDM screens.

### CODE REVIEW

**Review by GDYendell — COMMENTED** [review]
This all looks quite reasonable. It looks like it clashes with what @ulrikpedersen has done on dls-vendor-update-R3-3, though. Did you take what he did and add to it or was this done completely separately?

**Comment by ulrikpedersen** [comment]
Sorry, I haven't had time to review this - and its not looking like I will have time to do it properly for a good while now (holidays coming up soon). 

It would definitely be preferred if it can be merged/reconciled with my dls-vendor-update-R3-3 branch - as I aim to release that for our RHEL7 environment...

**Comment by GDYendell** [comment]
It does build on https://github.com/dls-controls/ADCore/tree/TimeSeriesPlugins-fix-do-not-merge with a small patch, but that conflicts with upstream changes so maybe we should leave it for now.

**Comment by BenBradnick** [comment]
I developed the support separately so there is a small difference in the builder support. In my case it also creates an instance of NDTimeSeriesN.template per signal specified for the time series plugin. This just adds a waveform record for each signal so you can get the time series over channel access, which in my case is used for plotting in the embedded EDM screen I created. So I could separate this out to make the builder support the same as dls-vendor-update-R3-3, and then you could instantiate individual NDTimeSeriesN templates.

This pull request also includes adding support for the NDFFT plugin which calculates the 1D/2D FFT of an input NDArray. I don't believe there is support for this in dls-vendor-update-R3-3.

**Pull request merged**
