### PR TITLE
Merge upstream 2-6 release

### PR DESCRIPTION
**Pull request by GDYendell**
With 2-6 being released, I have done a fresh merge today (on top of Alan's recent internal dls release, 2-4dls8). Firstly merging 2-5, then moving the opi files to avoid conflicts and then merging 2-6.

I still need to update the dependencies on Asyn and Busy once they are updated, but building with my own versions in my home works fine and the tests pass (same with the travis build as it is set up to clone Asyn 4-31).

By editing built RELEASE files I got simDetector to build as before, ~~but I get a seg fault when it runs. Possibly something has gone wrong with the merge this time, but more likely I made a mistake when editing the files to make it build... I will continue to look into that~~. It works without ~~the file plugins~~ netCDF, Magick and Nexus once I comment out the pva stuff as the pvaDriver.template has been moved to it's own repository.

### CODE REVIEW

**Review by ajgdls — COMMENTED** [review]
Annoying difference but it doesn't matter I guess.

**Review by ajgdls — COMMENTED** [review]
Oops I thought I was reviewing a single item - sorry!
OK generally it looks fine to me.  There are one or two odd spaces which are annoying but not important.  The only code difference I could see was the recent SWMR flush change which is good.  Lots of new DLS opi files in their own directory.  One other comment is the DB Makefile, where we appear to be installing extra templates not present in the ADCore master branch DB Makefile.

**Comment by GDYendell** [comment]
I will re-do the merge to resolve the conflict in ADApp/Db/Makefile to not duplicate entries, once Ulrik points out any problems.

**Comment by ulrikpedersen** [comment]
Thanks Gary. I've just noticed this and I will take a closer look this afternoon.

**Review by ulrikpedersen — CHANGES_REQUESTED** [review]
The op/opi/symbols dir probably belongs inside the op/opi/dls/  dir.

There are a couple of unnecessary white-space diffs in  ADApp/pluginTests/Makefile

I have still to do a compare of the merge with the upstream master and check that I see only DLS configuration changes...

**Comment by ajgdls** [comment]
You will see the change I made very recently to fix SWMR flushing.   You will also see the change to stop spam error messages by initialisation of parameters.  Those two should be acceptable.

**Comment by ulrikpedersen** [comment]
> I have still to do a compare of the merge with the upstream master and check that I see only DLS configuration changes...

I've had a look at the differences and they appear to be restricted to DLS configurations, OPI files etc.  I also noticed the changes that Alan mention:

> You will see the change I made very recently to fix SWMR flushing. You will also see the change to stop spam error messages by initialisation of parameters. Those two should be acceptable.

I'm happy with this. :+1:

**Comment by GDYendell** [comment]
OK so just so we know where we are, I will do the merge again with

* Duplicate entries in ADApp/Db/Makefile removed
* Whitespace in ADApp/pluginTests/Makefile removed
* symbols/ moved into dls/ folder

**Comment by GDYendell** [comment]
I have made a fresh pull request with these changes here #10

**Comment by ulrikpedersen** [comment]
If can just push the changes to the same branch "new-merge" and this Pull Request will stay open and reflect the changes (even if you need to --force  push). That way we can retain the history of the comments and review together with the PR as part of the merge history...

Ref. #10

**Pull request merged**
